version: '3.9'

services:
  
  compute-node-service-provisioner:
    env_file:
      - env.dev
    image: pennsieve/compute-node-service-provisioner
    volumes:
      - ./terraform:/service/terraform
      - $HOME/.aws:/root/.aws:ro
    container_name: compute-node-service-provisioner
    build:
      context: .
      dockerfile: ./Dockerfile